/* WE BARE BEARS — Episode Directory Data
   Format: [season, epInSeason, title, shortDesc, ytId|null] */
var WBB_EPISODES = [
// ── Season 1 (2015–16) ──────────────────────────────────────
[1,1,'Our Stuff','The bears chase their stolen backpack across the whole city.',null],
[1,2,'Viral Video','Grizz films a video to make the bears internet famous.','oZC4iG1aC7w'],
[1,3,'Food Truck','The bears\' food truck accidentally becomes the hottest spot in town.','bGUjrjhHDQI'],
[1,4,'Chloe','A child prodigy studies the bears for her college presentation.',null],
[1,5,'Panda\'s Date','Panda falls for a saleswoman at the farmer\'s market.','WOSqCVt29Z0'],
[1,6,'Everyday Bears','A peek at each bear\'s hilariously chaotic daily routine.','CdkroTj_cbE'],
[1,7,'Burrito','Grizz becomes dangerously obsessed with a giant bear-sized burrito.','yG2io-7OyyQ'],
[1,8,'Primal','Grizz drags his brothers into the woods to test their survival skills.','8gN8AfhqRQI'],
[1,9,'Jean Jacket','A lucky denim jacket causes the bears to fight over who gets to wear it.','cAXz46iqbgM'],
[1,10,'Nom Nom','A famous koala begs the bears to help him regain his viral fame.','NZE1JWmW08k'],
[1,11,'Shush Ninjas','The bears become stealth ninjas to silence rowdy moviegoers.','bJISvmC0Ut4'],
[1,12,'My Clique','The bears throw a cave party to help Chloe connect with college classmates.','0mqSm4kO3Iw'],
[1,13,'Charlie','A Bigfoot named Charlie moves in and nearly destroys the cave.','s9pamjYy_SU'],
[1,14,'Brother Up','Panda accidentally dethrones Grizz as the bears\' leader.','WdPPeM4FvgU'],
[1,15,'Occupy Bears','The bears battle construction workers threatening their cave.','mNfNSAz48pU'],
[1,16,'Panda\'s Sneeze','Panda\'s adorable sneeze video goes viral and eclipses Nom Nom\'s fame.','Fsmp-3LSsUk'],
[1,17,'The Road','Baby bears try to sell themselves from a cardboard box roadside.','l78Vx-gVRFk'],
[1,18,'Emergency','Grizz must race to the hospital after a crab pinches his ear.','EOrPHXdgYSI'],
[1,19,'Tote Life','The bears enthusiastically embrace the reusable bag craze.','wnUr-LZDRKY'],
[1,20,'Charlie & The Snake','Charlie befriends a forest snake while foraging food for the bears.','SO0H-u8VV1I'],
[1,21,'Video Date','Panda video-dates a French girl but his brothers fall for her too.','b-i084mfK-o'],
[1,22,'Pet Shop','Baby bears try to get adopted by starring in a pet shop commercial.','m8Gmw6mLxyM'],
[1,23,'Chloe and Ice Bear','Chloe and Ice Bear explore the city searching for a shared interest.','dTWp3xTlnS8'],
[1,24,'Cupcake Job','The bears work at a cupcake shop to pay for their broken laptop.','9vbIGu0syng'],
[1,25,'Hibernation','Grizz discovers he is the only brother who can actually hibernate.','uHej3Ga7I-E'],
[1,26,'Charlie Ball','Charlie joins the bears\' basketball team and instantly dominates.',null],
// ── Season 2 (2016–17) ──────────────────────────────────────
[2,1,'Yard Sale','Free stuff from a yard sale leads to three separate chaotic adventures.',null],
[2,2,'Slumber Party','A hailstorm forces Chloe to spend the night at the bears\' cave.',null],
[2,3,'Bear Cleanse','The bears go on a natural diet but hopelessly can\'t break old habits.',null],
[2,4,'Nom Nom\'s Entourage','After a humiliating prank, Nom Nom hires the bears as his entourage.',null],
[2,5,'Ranger Tabes','An overzealous forest ranger helps the bears find their missing package.',null],
[2,6,'Rooms','The bears switch rooms and uncover surprising secrets about each other.',null],
[2,7,'Losing Ice','Feeling ignored, Ice Bear quits to become a chef at a Japanese grill.',null],
[2,8,'Cellie','Panda is consumed with envy when his brothers get shiny new smartphones.',null],
[2,9,'Fashion Bears','New outfits send each bear\'s life in a wildly different direction.',null],
[2,10,'The Island','Baby bears get stranded on a deserted island with two mysterious castaways.',null],
[2,11,'Bear Flu','After swimming in a dirty lake, the bears believe they have deadly bear flu.',null],
[2,12,'Chicken and Waffles','Panda navigates the city completely blind after breaking his contacts.',null],
[2,13,'The Audition','The bears audition to become the mascot for their favourite cereal brand.',null],
[2,14,'Captain Craboo Pt. 1','The bears reunite with pet crab Craboo — who puts them on trial.',null],
[2,15,'Captain Craboo Pt. 2','On the run from the law, the bears race to set Craboo free at the ocean.',null],
[2,16,'Baby Bears on a Plane','Baby bears cause international havoc on a flight to Sweden.',null],
[2,17,'Yuri and the Bear','Baby Ice Bear meets a mysterious Russian man who teaches him arctic survival.',null],
[2,18,'Icy Nights','Ice Bear navigates the city underground to reclaim his stolen Roomba.',null],
[2,19,'Everyone\'s Tube','A compilation of the bears\' many uploaded musical videos.',null],
[2,20,'Creature Mysteries','The bears race to protect Charlie when Ranger Tabes starts investigating.',null],
[2,21,'The Library','The bears\' study help gives Chloe a sugar rush before her big exam.',null],
[2,22,'Grizz Helps','Grizz spends the day helping strangers and ends up chasing a lost chicken.',null],
[2,23,'Christmas Parties','The bears try to attend four Christmas parties in a single night.',null],
[2,24,'Subway','Stranded on a subway platform, the bears recover their scattered belongings.',null],
[2,25,'Panda\'s Friend','Panda befriends his lookalike Tom, who turns dangerously obsessive.',null],
[2,26,'Neighbors','An elderly couple camping by the cave has a very suspicious bear history.',null],
// ── Season 3 (2017–18) ──────────────────────────────────────
[3,1,'Grizzly: The Movie','Grizz is cast in a movie that turns out to be a killer-bear horror film.',null],
[3,2,'Anger Management','Nom Nom must do anger management with Grizz as his unlikely therapist.',null],
[3,3,'$100','Baby bears find a $100 bill and desperately try to protect it from thieves.',null],
[3,4,'Professor Lampwick','The bears kidnap Chloe\'s sadistic professor to help fix her failing grade.',null],
[3,5,'Ralph','Charlie befriends Ralph the Bigfoot, who turns out to be a cruel prankster.',null],
[3,6,'Planet Bears','A BBC-style nature documentary covers the bears\' morning grocery run.',null],
[3,7,'Coffee Cave','The bears turn the cave into a coffee shop — with disastrous caffeinated results.',null],
[3,8,'Charlie\'s Big Foot','Charlie hurts his foot and the bears must smuggle him into a hospital.',null],
[3,9,'The Demon','Chloe and Ice Bear battle the terrifying neighbour dog for a lost hoodie.',null],
[3,10,'Panda\'s Art','An art dealer covets Panda\'s painting of Charlie, forcing him to reclaim it.',null],
[3,11,'Poppy Rangers','Grizz and Ranger Tabes clash while leading young girls on a cave expedition.',null],
[3,12,'Lucy\'s Brother','Panda babysits Lucy\'s allergic younger brother trying to impress her.',null],
[3,13,'The Fair','Baby bears become carnival prizes hoping to be won and taken home.',null],
[3,14,'Private Lake','The bears accidentally reveal Charlie\'s secret private lake on social media.',null],
[3,15,'Lunch with Tabes','Tabes goes full detective mode when her lunch is stolen at a restaurant.',null],
[3,16,'Road Trip','The bears and Chloe road trip to see a meteor shower, picking up a hitchhiker.',null],
[3,17,'Summer Love','Panda goes on a mission to return a phone to the girl of his dreams.',null],
[3,18,'The Kitty','The bears adopt a kitten that turns out to be a cougar cub.',null],
[3,19,'Crowbar Jones','Grizz screens his epic amateur movie to an increasingly restless focus group.',null],
[3,20,'Kyle','A koala named Kyle claims to be Nom Nom\'s long-lost brother.',null],
[3,21,'Citizen Tabes','After quitting her ranger job, Tabes starts an online craft business.',null],
[3,22,'Dance Lessons','Panda agrees to partner Lucy in a dance contest but she is terrible.',null],
[3,23,'Icy Nights II','Ice Bear must rescue his friend Yana from a sinister cyber-villain.',null],
[3,24,'Dog Hotel','Grizz causes a roach infestation, forcing the bears into a dog hotel.',null],
[3,25,'Bear Lift','The bears use the bear stack as a ride-share taxi to save Darrell\'s store.',null],
[3,26,'The Nom Nom Show','All of Nom Nom\'s TV guests bail — the bears step in as replacements.',null],
[3,27,'Ice Cave','Ralph hijacks the cave overnight and turns it into a frozen fortress.',null],
[3,28,'Spa Day','A relaxing spa day goes uniquely and hilariously for each bear.',null],
[3,29,'Charlie\'s Halloween Thing','Charlie tells two scary Halloween stories to trick-or-treaters.',null],
[3,30,'Bunnies','Baby bears protect a bunny burrow from an attacking crow gang.',null],
[3,31,'Pigeons','Grizz befriends pigeons who are secretly part of a criminal pigeon cartel.',null],
[3,32,'Panda 2','A stuffed panda convinces Baby Panda to sneak out of his enclosure.',null],
[3,33,'Tubin\'','The bears go river tubing and Panda ends up stranded in a vegan tribe.',null],
[3,34,'Lazer Royale','Baby bears\' laser tag game transforms into an all-out warzone.',null],
[3,35,'Ranger Games','Tabes leads the Poppy Rangers in a fierce kickball tournament.',null],
[3,36,'The Perfect Tree','Chloe and Ice Bear trek north to find the perfect Christmas tree.',null],
[3,37,'Bearz II Men','Baby bears disguise as a teen\'s guardian to help him win a talent show.',null],
[3,38,'Bro Brawl','The bears vs Tom\'s friend group on a brother-themed game show.',null],
[3,39,'Hurricane Hal','A hurricane splits the bears across three separate locations in the city.',null],
[3,40,'Vacation','Nom Nom\'s stress spikes dangerously — Grizz becomes his comfort bear.','oYF0zJyOk9w'],
[3,41,'Beehive','Bear honey addiction turns the cave into a full beehive serving a queen bee.',null],
[3,42,'The Park','Each bear has a separate adventure during what should be a quiet park day.',null],
[3,43,'I Am Ice Bear','After a head injury, Ice Bear develops a talkative outgoing personality.',null],
[3,44,'Baby Bears Can\'t Jump','Baby bears play basketball for pizza and learn their signature Bearstack.',null],
// ── Season 4 (2018–19) ──────────────────────────────────────
[4,1,'Go Fish','The bears discover an unusual past connection with a giant orange fish.',null],
[4,2,'Teacher\'s Pet','Baby bears become star students but earn every classmate\'s hatred.',null],
[4,3,'Googs','Panda wins a tech-giant tour and nearly gets launched into space.',null],
[4,4,'Paperboyz','Baby bears\' paper delivery contest turns the brothers against each other.',null],
[4,5,'Bear Squad','Tabes deputizes the bears to catch a fox stealing everyone\'s belongings.',null],
[4,6,'Lil\' Squid','Baby bears help a baby squid find its family in a dangerous aquarium.',null],
[4,7,'I, Butler','Ice Bear\'s rebuilt robot clone becomes a terrifying cleaning machine.',null],
[4,8,'Family Troubles','Baby Grizz stars in a Canadian sitcom and faces a new rival cast member.',null],
[4,9,'Best Bears','The bears rush to save Darrell\'s wedding — but the groom gets cold feet.',null],
[4,10,'Crowbar Jones: Origins','Grizz pitches his unfinished Crowbar Jones film to a reluctant Nom Nom.',null],
[4,11,'Hot Sauce','The pigeon cartel is stealing the city\'s entire hot sauce supply.',null],
[4,12,'Mom App','The bears hire three surrogate moms via an app — none of them work out.',null],
[4,13,'The Limo','To cheer up Panda after Lucy gets a boyfriend, the bears throw a limo party.',null],
[4,14,'More Everyone\'s Tube','Another musical video compilation from the bears and their friends.',null],
[4,15,'Money Man','The bears help Chloe present her mind-reading device at a college contest.',null],
[4,16,'Rescue Ranger','Tabes finally meets Charlie — who is then captured by a Yowie hunter.',null],
[4,17,'El Oso','In 1913 Mexico, Charlie befriends a minor criminal pursued by a dangerous gang.',null],
[4,18,'Charlie\'s Halloween Thing 2','Charlie hosts four more horror tales including zombies and wish machines.',null],
[4,19,'Escandalosos','Baby bears become luchadors to win prize money for an injured Rodolfo.',null],
[4,20,'Pizza Band','The bears replace a broken animatronic pizza band and accidentally go on tour.',null],
[4,21,'Adopted','Baby bears are auctioned to an eccentric millionaire — as his gorilla\'s toys.',null],
[4,22,'Wingmen','The bears help a rare, extremely loud bird find a mate so they can sleep.',null],
[4,23,'Braces','Panda\'s ugly new braces give him accidental control over electrical devices.',null],
[4,24,'Christmas Movies','Baby bears catch a thief posing as Santa inside a video rental store.',null],
[4,25,'Imaginary Friend','The baby bears\' imaginary superhero causes very real and very big problems.',null],
[4,26,'The Mall','The bears and the Bros each have wild separate adventures in the same mall.',null],
[4,27,'Tunnels','Moles beneath the cave have built a manga-worshipping underground civilization.',null],
[4,28,'Ramen','Baby bears help a struggling ramen chef impress her demanding father.',null],
[4,29,'The Gym','Each bear tackles a different gym class with unexpectedly absurd results.',null],
[4,30,'Bubble','Panda\'s germaphobia leads him to live full-time inside a plastic bubble.',null],
[4,31,'Baby Orphan Ninja Bears','Baby bears train under a ninja master to stop a criminal gang in NYC sewers.',null],
[4,32,'Fire!','Grizz becomes a fire marshal dangerously obsessed with extinguishing every flame.',null],
[4,33,'Ranger Norm','The replacement ranger is secretly an illegal agent planning to raze the forest.',null],
[4,34,'Shmorby','The bears\' AI home assistant makes them so lazy they become enormous.',null],
[4,35,'Snake Babies','Charlie adopts six hatched snake babies as a single parent — chaos follows.',null],
[4,36,'Sandcastle','Baby Panda falls in love while building an elaborate sandcastle home.',null],
[4,37,'Bros in the City','The bears and Bros navigate relationship drama on a hit reality TV show.',null],
[4,38,'Cousin Jon','The bears help Chloe get revenge on her legendary prankster cousin Jon.',null],
[4,39,'Lord of the Poppies','Left in charge of the Poppy Rangers, Grizz accidentally drives them feral.',null],
[4,40,'The Mummy\'s Curse','Baby bears must return a mummy\'s amulet to a museum by midnight.',null],
[4,41,'Band of Outsiders','Baby Ice Bear joins a gang of London rebels still grieving the loss of Yuri.',null],
[4,42,'Tabes & Charlie','Tabes and Charlie team up in a chicken costume to find her missing dog.',null],
[4,43,'Panda\'s Birthday','Grizz and Ice Bear take Panda to meet K-pop group Monsta X for his birthday.',null],
// ── Movie ────────────────────────────────────────────────────
['m',1,'We Bare Bears: The Movie','The bears face their greatest threat and must decide if they can stay together.',null]
];
